[theme]
base = "dark"
primaryColor = "#FBBF24"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0F0F14"
textColor = "#FFFFFF"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
